CREATE TABLE CLIENTES (
                          CLIENTE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          NOMBRE VARCHAR2(100) NOT NULL,
                          EMAIL VARCHAR2(100) UNIQUE NOT NULL,
                          TELEFONO VARCHAR2(20),
                          FECHA_REGISTRO DATE,
                          ACTIVO CHAR(1)
);

CREATE TABLE PRODUCTOS (
                           PRODUCTO_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           NOMBRE VARCHAR2(100) NOT NULL,
                           PRECIO NUMBER(10,2) NOT NULL,
                           STOCK NUMBER(10) NOT NULL
);

CREATE TABLE PEDIDOS (
                         PEDIDO_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         CLIENTE_ID NUMBER NOT NULL,
                         PRODUCTO_ID NUMBER NOT NULL,
                         CANTIDAD NUMBER(10) NOT NULL,
                         FECHA_PEDIDO DATE,
                         FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
                         FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID)
);
